### ISSUE TITLE
KeyError: 'attr'

### ISSUE THREAD

**Issue by wangjing60755** [MarsTechHAN/keras2ncnn#21]
运行 python -m keras2ncnn -i weights.h5 -o ./
出现

Reading and parsing keras h5df file...
Start graph optimizing pass...
        Removing unused nodes...
Traceback (most recent call last):
  File "D:\Anaconda3\envs\tf2-gpu\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Anaconda3\envs\tf2-gpu\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda3\envs\tf2-gpu\lib\site-packages\keras2ncnn\__main__.py", line 12, in <module>
    sys.exit(_main())
  File "D:\Anaconda3\envs\tf2-gpu\lib\site-packages\keras2ncnn\keras2ncnn.py", line 60, in main
    GraphOptimization.removing_unused_nodes(keras_graph)
  File "D:\Anaconda3\envs\tf2-gpu\lib\site-packages\keras2ncnn\graph_optimizer.py", line 9, in removing_unused_nodes
    if graph.get_node_attr(target_node_name)[
  File "D:\Anaconda3\envs\tf2-gpu\lib\site-packages\keras2ncnn\graph_tool.py", line 103, in get_node_attr
    return self.graph[name]['attr']
KeyError: 'attr'

**Comment by MarsTechHAN** [comment]
Can you provide your model file? Seems like there is something wrong with your model structure.

**Comment by wangjing60755** [comment]
[weights_179-0.9241.zip](https://github.com/MarsTechHAN/keras2ncnn/files/6008850/weights_179-0.9241.zip)

**Comment by wangjing60755** [comment]
之前模型是在tf2.0中报错KeyError: 'attr'；
改为tf1.9，报错变了：
Operator SeparableConv2D not support.
不支持SeparableConv2D

**Comment by MarsTechHAN** [comment]
Here is the reason for the Key Error:
![image](https://user-images.githubusercontent.com/10462805/109504550-a2ed9000-7ad6-11eb-830e-8ee729085c64.png)
I am considering how to support the layer...hmm....

**Comment by MarsTechHAN** [comment]
Fixed 71dbf085919e21e25e4b413f5c18395a5445c106
