### ISSUE TITLE
AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by wo712268** [MarsTechHAN/keras2ncnn#22]
I tried to convert my model:
python3 -m keras2ncnn -i HOME.h5 -o .
But it reports issues like this:
(ncnn) micang@micang-X3:~$ python3 -m keras2ncnn -i HOME.h5 -o ./ 
Reading and parsing keras h5df file...
Traceback (most recent call last):
  File "/home/micang/anaconda3/envs/ncnn/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/micang/anaconda3/envs/ncnn/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/micang/anaconda3/envs/ncnn/lib/python3.7/site-packages/keras2ncnn/__main__.py", line 12, in <module>
    sys.exit(_main())
  File "/home/micang/anaconda3/envs/ncnn/lib/python3.7/site-packages/keras2ncnn/keras2ncnn.py", line 55, in main
    H5dfParser(args.input_file).parse_graph(keras_graph)
  File "/home/micang/anaconda3/envs/ncnn/lib/python3.7/site-packages/keras2ncnn/h5df_parser.py", line 10, in __init__
    self.model_config = json.loads(model_config_raw.decode('utf-8'))
AttributeError: 'str' object has no attribute 'decode'

After i upgrade my keras2ncnn to vertion 0.1.4, it still happens:
2021.02.10
(ncnn) micang@micang-X3:~$ python3 -m keras2ncnn -i HOME.h5 -o ./
Reading and parsing keras h5df file...
Traceback (most recent call last):
  File "/home/micang/anaconda3/envs/ncnn/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/micang/anaconda3/envs/ncnn/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/micang/anaconda3/envs/ncnn/lib/python3.7/site-packages/keras2ncnn/__main__.py", line 12, in <module>
    sys.exit(_main())
  File "/home/micang/anaconda3/envs/ncnn/lib/python3.7/site-packages/keras2ncnn/keras2ncnn.py", line 55, in main
    H5dfParser(args.input_file).parse_graph(keras_graph)
  File "/home/micang/anaconda3/envs/ncnn/lib/python3.7/site-packages/keras2ncnn/h5df_parser.py", line 40, in __init__
    self.keras_version = self.get_keras_version()
  File "/home/micang/anaconda3/envs/ncnn/lib/python3.7/site-packages/keras2ncnn/h5df_parser.py", line 59, in get_keras_version
    .attrs['keras_version'].decode('utf8')
AttributeError: 'str' object has no attribute 'decode'

**Comment by MarsTechHAN** [comment]
Hi, this should be the problem with the h5py, but I am not able to reproduce it in my own system (I have encounter it once). Can you share your version of all the libraries in your system and your model file?
In other to get the version of all your python libraries, you can run:
```bash
python3 -mpip freeze
```
and copy-paste the result here.

**Comment by MarsTechHAN** [comment]
Fixed 9980e9a9744351232558117b1c41feeb2c7d662a
