### ISSUE TITLE
'NoneType' object has no attribute 'decode'

### ISSUE THREAD

**Issue by weilanShi** [MarsTechHAN/keras2ncnn#6]
你好，感谢贡献，感谢开源！我尝试转ckpt 模型至ncnn, 先将ckpt 转为了 .h5, 再使用你的方法转为ncnn , 在转的时候，报错如下：

Traceback (most recent call last):
  File "keras2ncnn.py", line 1477, in <module>
    H5dfParser(args.input_file).parse_graph(keras_graph)
  File "keras2ncnn.py", line 52, in __init__
    self.model_config = json.loads(model_config_raw.decode('utf-8'))
AttributeError: 'NoneType' object has no attribute 'decode'

model_config_raw 读出来为空，可以帮忙看下吗 ? 链接是我的 h5（out.h5） 文件 和 ckpt 转换后的pb(freeze_538000.pb)文件（pb测试过没问题），其余两个文件请忽略

https://github.com/weilanShi/caffemodel

**Comment by MarsTechHAN** [comment]
你的pb我看了一下，没有不支持的op，你这个h5 netron都打不开，一般来说肯定是转换出问题了。
我明天帮你转一下试试看吧，tf这个一堆模型转换的问题是真的头疼= =

**Comment by weilanShi** [comment]
> 你的pb我看了一下，没有不支持的op，你这个h5 netron都打不开，一般来说肯定是转换出问题了。
> 我明天帮你转一下试试看吧，tf这个一堆模型转换的问题是真的头疼= =

感谢大佬！tf 想在 ncnn下跑真的是太难了（就是钟情于ncnn, 莫得办法）

**Comment by nihui** [comment]
> > 你的pb我看了一下，没有不支持的op，你这个h5 netron都打不开，一般来说肯定是转换出问题了。
> > 我明天帮你转一下试试看吧，tf这个一堆模型转换的问题是真的头疼= =
> 
> 感谢大佬！tf 想在 ncnn下跑真的是太难了（就是钟情于ncnn, 莫得办法）

你这个错误我也遇到了，于是只能导出 mlir，然后 mlir2ncnn ...
